<?xml version="1.0" encoding="utf-8"?><Database Name="Glass" Class="GlassClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql;Initial Catalog=Glass;Persist Security Info=True;User ID=glass" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GlassConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StoredCredentials" Member="StoredCredentials">
    <Type Name="StoredCredential">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccessToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RefreshToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>